# Site settings
title: Alberto Pastor Moreno
description: Alberto Pastor Moreno personal portfolio
baseurl: "" # the subpath of the site
url: "https://albertopastormr.github.io/" 
avatar: "/assets/img/favicon.ico"
# User settings
username: Alberto Pastor Moreno
user_description: Passionate software developer who loves to design simple solutions for complex real-world problems through upcoming technologies and agile methodologies. Teamwork, hard work and the imperative desire to perform at the best level are the core for me as an everyday learner who never stop working out for reaching my greatest personal version.
user_title: Computer Science student
email: albertopastormr@gmail.com
twitter_username: albertopastormr
github_username:  albertopastormr
gplus_username:  /103154106735689134313
linkedin_username: /albertopastormr
medium_username: /albertopastormr

# Links
l_cs-degree: https://informatica.ucm.es/estudios/grado-ingenieriadelsoftware
l_jekyll: https://jekyllrb.com/
# Social networks links
l_my-email: mailto:albertopastormr@gmail.com
l_my-twitter: https://twitter.com/albertopastormr
l_my-gplus: https://plus.google.com/u/0/103154106735689134313
l_my-github: https://github.com/albertopastormr
l_my-instagram: https://instagram.com/albertopastormr
l_my-linkedin: https://www.linkedin.com/in/albertopastormr/
 #class="ref-link" a utilizar para projects

# Github repos links
l_gh-ifesoft: https://github.com/albertopastormr/ifesoft
l_gh-particle: https://github.com/nrandecker/particle
l_gh-particle-author: https://github.com/nrandecker


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
