# Site settings
title: Alberto Pastor Moreno
description: Alberto Pastor Moreno personal portfolio
baseurl: "" # the subpath of the site
url: "https://albertopastormr.github.io/" 
avatar: "/assets/img/favicon.ico"
# User settings
username: Alberto Pastor Moreno
user_description: Teamwork, hard work and the imperative desire to perform at the best level are the core for me as an everyday learner who never stop working out for reaching my greatest personal version.
user_title: Computer Science student
email: albertopastormr@gmail.com
twitter_username: albertopastormr
github_username:  albertopastormr
gplus_username:  /103154106735689134313
linkedin_username: /albertopastormr
medium_username: /albertopastormr

# Links
l_cs-degree: https://informatica.ucm.es/estudios/grado-ingenieriadelsoftware
# Social networks links
l_my-email: mailto:albertopastormr@gmail.com
l_my-twitter: https://twitter.com/twitter_username
l_my-gplus: https://plus.google.com/u/0{{gplus_username}}
l_my-github: https://github.com/{{page.github_username}}
 #class="ref-link"

# Github repos links
l_gh-ifesoft: https://github.com/albertopastormr/ifesoft
l_gh-particle: https://github.com/nrandecker/particle


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
